[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['npm ci --prefer-offline --no-audit']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
